### ISSUE TITLE
Check box «Draw slices»

### ISSUE THREAD

**Issue by yuriryzhenkov** [tarngerine/sketch-name-artboards#10]
Hi. Every time i turn off check box and every time it becomes turned on. I think the latest settings should be remembered by plugin.

**Comment by tarngerine** [comment]
Agreed - thanks for the request. On vacation Til next week and will add






On Thu, Aug 4, 2016 at 1:47 AM -0700, "yuriryzhenkov" <notifications@github.com> wrote:












Hi. Every time i turn off check box and every time it becomes turned on. I think the latest settings should be remembered by plugin.

**Comment by tarngerine** [comment]
this is fixeD! if you redownload/double click to reinstall, you'll be all set

**Comment by tarngerine** [comment]
https://github.com/tarngerine/sketch-name-artboards/releases/latest
