### ISSUE TITLE
Artboard label placement

### ISSUE THREAD

**Issue by 360spencer** [tarngerine/sketch-name-artboards#11]
In sketch 45:
When updating files with existing artboard labels, labels are not being replaced in proper area. 
When creating a new sketch file and pasting in old art boards, labels are not placed in proper area.
When creating a new sketch file with new artboards, plugin works as intended.

**Comment by tarngerine** [comment]
Thanks for the report. sketch just released 45.1 beta to fix some text issues. If you're on beta could you see if it fixes?
________________________________

**Comment by 360spencer** [comment]
Just updated to the 45.1 release (non-beta) still having issues

**Comment by tarngerine** [comment]
Ok I'll try to look into it when I have time the next few days. Sorry for delays - been out of town.

________________________________

**Comment by tarngerine** [comment]
hey, so i tried to reproduce this, but wasnt able to. do you have a specific file you can share with those existing labels + artboards? u can nuke the artboard contents/change the titles if it's confidential (and see if that reproduces)

also, can u show me screenshots of the "not properly placed" state? thanks

**Comment by lianggetiequan** [comment]
@tarngerine Thank you for your plugin. It helps me a lot in my work. I have the same problem with @360spencer .

[http://www.weibo.com/1493088061/Fbim246pD?ref=home&rid=0_0_8_3071743653598579955&type=comment#_rnd1499418297461](url)

Can you open this URL ?

**Comment by tarngerine** [comment]
Oh thanks for the screenshot. In future u can just paste image here in github too!

Can you send me that sketch file?
您能夠送我哪一個.sketch檔案嗎

**Comment by tarngerine** [comment]
ill be on vacation next week so i wont be able to fix this until later. the best fix for now is to create a new artboard and copy the contents over from the old artboards until one of you can send me your sketch file! thanks

**Comment by lianggetiequan** [comment]
haha.. I didn't even know how to paste image or file till you told me....
[for tarngerine.sketch.zip](https://github.com/tarngerine/sketch-name-artboards/files/1134302/for.tarngerine.sketch.zip)

**Comment by 360spencer** [comment]
Thanks I've attached a file. Enjoy your vacation. 
[Test-Artboard-Issue.sketch.zip](https://github.com/tarngerine/sketch-name-artboards/files/1135684/Test-Artboard-Issue.sketch.zip)

**Comment by 360spencer** [comment]
Updated to Sketch 45.2 and issue is still present.

**Comment by tarngerine** [comment]
Thanks! I'm back in town tomorrow so I'll take a look then
________________________________

**Comment by tarngerine** [comment]
hey all, sorry for the delay. finally got time today to figure it out. should be fixed if you redownoad the plugin now!

**Comment by tarngerine** [comment]
https://github.com/tarngerine/sketch-name-artboards/releases/tag/v1.5

**Comment by lianggetiequan** [comment]
thank you 
好赞，辛苦啦
